services:

  solr:
    build: .
    ports:
      - "8983:8983"
    healthcheck:
      interval: 5s
      timeout: 10s
      start_period: 10s
      retries: 5
      test: "curl -f --retry-connrefused http://solr:8983/solr/ptsearch/admin/ping"
