name: Docker Build

on:
  workflow_run:
    workflows: [ 'Run CI' ]
    branches: [ 'main' ]
    types: [ completed ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build image and push to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: 'ghcr.io/${{ github.repository }}-unstable:${{ github.sha }}, ghcr.io/${{ github.repository }}-unstable:latest'
          file: Dockerfile

    # TODO: automate deployment w/ argocd
    # for now - update image in
    # https://github.com/hathitrust/ht_tanka/blob/main/environments/ptsearch
