name: Run Tests

on:
  push:
    branches:
      - main

  pull_request:

jobs:
  # Run tests
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build docker image
        run: docker compose --file docker-compose.yml build

      - name: Run tests
        run: docker compose --file docker-compose.yml run solr curl -f --retry-connrefused --retry 5 --retry-delay 5 http://localhost:8983/solr/ptsearch/admin/ping
